[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pumpkinpie"
version = "1.0"
description = "A basic, slow python solver"
authors = [{ name = "llakala" }]
requires-python = ">=3.8"

[project.scripts]
pumpkinpie = "main:main"
